version: "3.8"

services:
    app:
        build: ./
        command:
            - 'ls'
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app

volumes:
    from-msg-check-data:
